language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install tox

script:
 - tox -e lint
 - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}

notifications:
  email:
    - tomaz+travisci@tomaz.me
